version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: shipment-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: shipmentdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  shipment-service:
    build: .
    container_name: shipment-service
    ports:
      - "8085:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shipmentdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123

volumes:
  mysql-data:
